
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: "circleci/node:dubnium-browsers"

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: sudo yarn global add bolt
      - run:
          name: Install Dependencies
          command: bolt install
      - run:
          name: Unit Tests
          command: bolt test
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: sudo yarn global add bolt
      - run:
          name: Install Dependencies
          command: bolt install --pure-lockfile
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken:$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Version package
          command: yarn release:version
      - run:
          name: Publish package
          command: yarn release:publish


workflows:
  version: 2
  test-deploy:

    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
